# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Create release"
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Create release"
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true

      - name: "Upload phar"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./slack-status-updater.phar
          asset_name: slack-status-updater.phar
          asset_content_type: application/x-php

      - name: "Upload phar.asc"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./slack-status-updater.phar.asc
          asset_name: slack-status-updater.phar.asc
          asset_content_type: application/pgp-signature
